service: cadastro-pacientes

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1

functions:
  listarPacientes:
    handler: handler.listarPacientes
    events:
      - http:
          path: pacientes
          method: get
  obterPaciente:
    handler: handler.obterPaciente
    events:
      - http:
          path: pacientes/{id}
          method: get
